name: musicianapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^4.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  cloud_firestore_web: ^2.6.7
  geoflutterfire: ^3.0.2
  video_player: ^2.2.18
  tiktoklikescroller: ^0.1.10
  google_sign_in: ^5.2.4
  firebase_auth: ^3.3.7
  flutter_signin_button: ^2.0.0
  provider: ^6.0.2
  firebase_storage: ^10.2.9
  file_picker: ^4.5.0
  image_picker: ^0.8.4+11
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.2
  geolocator: ^8.2.0
  video_compress: ^3.1.0
  image_crop: ^0.4.0
  flutter_image_compress: ^1.1.0
  salomon_bottom_bar: ^3.2.0
  google_fonts: ^2.3.1
  circle_button: ^1.1.0
  font_awesome_flutter: ^9.2.0
  badges: ^2.0.2
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  image_cropper: ^1.5.0
  expandable: ^5.0.1
  chewie: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/img/welcome-image.png


  uses-material-design: true

